<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TimeTracker.UpdateHelper</AssemblyName>
    <RootNamespace>TimeTracker.UpdateHelper</RootNamespace>
    <!-- Sem console piscando na atualização -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
